### PR TITLE
Refactor: better handling of dynamic properties for Entities

### PR DESCRIPTION
**Pull request by alesinicio**
Introduce usage of magic __set and __get methods to handle dynamic properties in Entities class.

#1375

### CODE REVIEW

**Comment by noplanman** [comment]
@TiiFuchs This should be ok to merge, yes?

Or was there something else you wanted to have in here?

**Comment by TiiFuchs** [comment]
I'm not that fond of the property name being "parameters".
Telegram calls them "fields" in their documentation, PHP usually calls them "properties". Parameters are the one on functions. That's misleading.

I vote renaming them to "fields".

Additionally: Should we throw an Exception when accessing a non-defined field?
That's not exactly the previous behavior, previously you would at least get a warning. Now nothing.

An Exception would help, since most of those Classes get their fields set from the incoming API Update. So if you access $update->mssage it was 100% an error, that get's undetected.

Let's merge it but rename the field, and add a throw there. What do you think, @noplanman ?

**Comment by noplanman** [comment]
@TiiFuchs Go for it!

**Comment by TiiFuchs** [comment]
I added the discussed refactoring and changed the `jsonSerialize()` method as well.
See https://github.com/php-telegram-bot/core/pull/1397

**Pull request merged**
