### PR TITLE
API 4.3 - Seamless Telegram Login

### LINKED ISSUE #955: Bot API 4.3
https://core.telegram.org/bots/api#may-31-2019

- [x] New entity `LoginUrl`.
- [x] Add the field `login_url` to the `InlineKeyboardButton` entity.
- [x] Add the field `reply_markup` to the `Message` entity.

### PR DESCRIPTION
**Pull request by noplanman**
Closes #955

### CODE REVIEW

**Comment by noplanman** [comment]
This should be good to go, if somebody could add their eyes to check, that would be sweet :muscle: 

@php-telegram-bot/developers

**Comment by rick20** [comment]
@noplanman is there any example how to use the seamless telegram login?
Spent the entire day digging for clue just to find out how to use this login_url but couldnt get anything.
https://core.telegram.org/api/url-authorization didnt help at all
thank you, i really appreciate your work

**Comment by ossiach** [comment]
> @noplanman is there any example how to use the seamless telegram login?
> Spent the entire day digging for clue just to find out how to use this login_url but couldnt get anything.

What exactly is your problem?

If you don't know how to send the login button to a user/group then this code example might be useful:
```
$login_object = new LoginUrl([
	'url' => 'https://mydomain.com/check_authorization.php',
	'request_write_access' => true,
]);

$login_keyboard = new InlineKeyboard([
	['login_url' => $login_object, 'text' => 'Click this button to login'],
]);


$data = [
	'chat_id' => $receiverChatId,
	'reply_markup' => $login_keyboard,
	'text'   => 'This is a basic text message with a login button beneath',
];
Request::sendMessage($data);
```

Don't forget that you have to link the domain first to your bot or otherwise the login button probably won't work as intended. To link a specific domain to your bot send the ```/setdomain``` Command to the [@botfather](t.me/botfather).

The message received by this code example should have a login button beneath it. If the user clicks on it, Telegram will open the specified URL in a browser. The PHP File behind this URL now has to verify the authenticity of the received information. If everything works fine, the user will be logged in on your website.

If you are struggling with the authorization part on the web server, I would recommend [the official guide for the Telegram Login Widget](https://core.telegram.org/widgets/login#receiving-authorization-data), because the authorization for the Login Widget works exactly the same way as the Seamless Telegram Login. In fact, if you have already integrated the Telegram Login Widget on your website, you can link the Seamless Login URL to the authorization file from your Login Widget and it will work without any further configuration needed.

If you don't know how implement the authorization file itself, I can recommend [this code example](https://gist.github.com/anonymous/6516521b1fb3b464534fbc30ea3573c2). I am using the ```check_authorization.php``` code myself for my own bot.

I hope these tips can help you (and everyone else stumbling across this topic).

**Comment by rick20** [comment]
@ossiach @noplanman apologize for double post my question.

As my comment in #1065 what I’ve got so far:
- write exactly the same code just like what you said
- got the inline button showing up below my bot message
- got the login confirmation dialog showing up when I click the inline button

However, when my page was opened, I see there’s no query string appended to my auth url. It’s just like a normal page, the exact same url I set in LoginUrl.

The documentation [here](https://core.telegram.org/api/url-authorization) talk about messages.acceptUrlAuth and urlAuthResultAccepted but there’s no guide on how to use it.
Are those parameters something I should care to know?

**Comment by noplanman** [comment]
Will move this conversation to your initial issue, so others can find the solution more easily...

#1065

**Pull request merged**
