### PR TITLE
Add laravel migrations

### PR DESCRIPTION
**Pull request by mithek**
This pull requests contains a laravel service provider to import the migrations.
It also contains the migrations based of the structure.sql

This pull request should make it easier for laravel programmers to use this package with migrations.

### CODE REVIEW

**Comment by jacklul** [comment]
It needs to be integrated with custom table prefix, you assumed usage of `telegram_` prefix which not everyone will be using!

**Comment by mithek** [comment]
@jacklul I've moved the prefix to a config file. I also added the config file within the laravel service provider.  I'm not sure how I can add my latest commit to the PR.

**Comment by noplanman** [comment]
Hi @mithek 

First of all, thanks for the PR and your idea / implementation!
Sorry for the delayed response from my side.

The topic of migrations has been raised and discussed a long while ago here: #112 
Since 0.45.0 onward (which is still very recent as of writing), simple SQL update scripts are the easiest to manage, without adding extra complexity / dependencies to the project.

We are well aware that a new DB layer / ORM should be implemented, but at the moment there just aren't enough resources for this 😕 

There are various projects out there that manage DB migrations, so we'd need to decide which approach to take when the time comes.

For the above reasons, I'll close this PR for now, but we'll definitely get back to it should we take the Laravel migration approach!

It would be best to first post an issue with an idea that can be discussed, before implementing something, just to keep unused code to a super-minimum 😉

**Comment by jacklul** [comment]
Just want to add this topic might come back once we decide to support multiple database drivers.

**Pull request closed without merging**
