### PR TITLE
Feat: allow dynamic properties for PHP8.2

### PR DESCRIPTION
**Pull request by alesinicio**
Add `AllowDynamicProperties` attribute to Entities.php for PHP8.2 compatibility. Not a permanent/final solution, but good enough to allow upgrades.

#1375

### CODE REVIEW

**Comment by noplanman** [comment]
@TiiFuchs Happy to do this for now?

**Comment by TiiFuchs** [comment]
Yeah we had this coming. Need to add `#[AllowDynamicProperties]` for now...

**Comment by TiiFuchs** [comment]
(Those checks are not very useful at all at the moment 😞)

**Comment by TiiFuchs** [comment]
For the record I'l cross-reference this issue in which we discussed this topic before: https://github.com/php-telegram-bot/core/issues/1375

**Pull request merged**
