### PR TITLE
issue #323 modify getCommandObject and executeCommand for possibility…

### PR DESCRIPTION
**Pull request by Jonybang**
For issue: Mess with custom command loading (#323)

Was add possibility to use custom namespace for commands. The code is tested on a real project and works well with two parallel bots. Also backward compatibility is observed

### CODE REVIEW

**Comment by gianlup** [comment]
Please merge this feature.

**Comment by VoDmAl** [comment]
@Jonybang, looks interesting. 

But I think all we need is just to use PSR-4.

**Comment by edwinfinch** [comment]
Any chance that this will ever be integrated?

**Comment by noplanman** [comment]
@Jonybang and all others here, please excuse my delay on this, just wasn't sure about how the future of the commands system will look like.

So until there is a clearer view, this is a great addition, thanks so much!

**Comment by Jonybang** [comment]
3 years delay, not a big deal though 😁

**Comment by noplanman** [comment]
I know, so so sorry 🙈
Can you confirm that the latest version works correctly for you?

Then we can get this merged and I'll release the next version.

**Comment by Jonybang** [comment]
> I know, so so sorry 🙈
> Can you confirm that the latest version works correctly for you?
> 
> Then we can get this merged and I'll release the next version.

sorry, since the last year i haven't my php environment, but if you can run two bots in the same time with this code - everything is okay 😊
I can show example of running two bots - if it will help

**Comment by noplanman** [comment]
>  I can show example of running two bots - if it will help

Yes please!

Do you mean running two bots in parallel, or using the same code but a different config for each bot?

**Comment by Jonybang** [comment]
In my laravel api routes i've defined two POST routes:
```
Route::post('/telegram/' . config('services.telegram.bot_1_token'), function (Request $request) {

    $telegram = new \Longman\TelegramBot\Telegram(config('services.telegram.bot_1_token'), config('services.telegram.bot_1_username'));

    $telegram->addCommandsPath(app_path('Console/Commands/Bot1'));
    $telegram->enableAdmins(config('bot_1.admins'));
    $telegram->handle();
    return 'ok';
});

Route::post('/telegram/' . config('services.telegram.bot_2_token'), function (Request $request) {
    $telegram = new \Longman\TelegramBot\Telegram(config('services.telegram.bot_2_token'), config('services.telegram.bot_2_username'));

    $telegram->addCommandsPath(app_path('Console/Commands/Bot2'));
    $telegram->enableAdmins(config('bot_2.admins'));
    $telegram->handle();
    return 'ok';
});
```
Commands of Bot1 i've stored in `app/Console/Commands/Bot1` directory with files `CallbackqueryCommand.php`, `GenericmessageCommand.php` and `StartCommand.php` as well as Bot2 in `app/Console/Commands/Bot2` directory

**Comment by noplanman** [comment]
@Jonybang Right, thanks. That will still work without problems 👍

**Pull request merged**
