### PR TITLE
Implement Telegram Games platform.

### LINKED ISSUE #726: Telegram Games!
https://core.telegram.org/bots/api#games

It's about time to get this in...

### PR DESCRIPTION
**Pull request by noplanman**
Finally add the Telegram Games platform!

WIP because it needs to be tested first ❗️ 

Closes #726

### CODE REVIEW

**Comment by noplanman** [comment]
Since nobody seems to have a game to test this, I think we just merge and wait for feedback from anybody who uses it down the line.

What do you guys think?
@php-telegram-bot/developers @chuv1 @Hitmare

**Comment by SirDerpington** [comment]
I'd like to test this but I guess I can't fetch it locally since I don't have the rights to do so?

Maybe you could indeed merge it and then let me update it to test it then?

**Comment by noplanman** [comment]
@SirDerpington You should be able to just fetch it from my branch, it's public.

Are you familiar with git? You can add my repo as a remote and then check out the branch:
```bash
$ git remote add noplanman https://github.com/noplanman/php-telegram-bot
$ git checkout noplanman/726-games
```

or if you've simply used composer to fetch the project, you could just fetch my branch directly.
Change your `composer.json` to use my repo and get the correct branch, then simply `composer install` it to get it :+1: 
```json
{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/noplanman/php-telegram-bot"
        }
    ],
    "require": {
        "longman/telegram-bot": "dev-726-games"
    }
}
```

**Comment by SirDerpington** [comment]
@noplanman Sorry, I've been working on something else the last two weeks. I think I can take a look at it next week.
It's stll on my todo list since we need that feature sooner or later!

**Comment by akalongman** [comment]
@noplanman please update your branch with current

@SirDerpington did you found time for testing this feature?

**Pull request merged**
