### PR TITLE
Bot API 6.3

### PR DESCRIPTION
**Pull request by TiiFuchs**
Todo in #1370

### CODE REVIEW

**Comment by noplanman** [comment]
This is looking good, thanks!! :smiley: 

Update the changelog and readme (to API 6.3) and then we should be ok to release.

**Comment by TiiFuchs** [comment]
Always forgetting something ;D
I'm on it...

**Comment by TiiFuchs** [comment]
Done.

**Comment by jyxjjj** [comment]
```
forum_topic_created
forum_topic_closed
forum_topic_reopened
```
added to Message::`subEntities` but not added to Message::`getType`

**Pull request merged**
