### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by p1ratrulezzz**

### CODE REVIEW

**Comment by akalongman** [comment]
@p1ratrulezzz what is this??

**Comment by noplanman** [comment]
@p1ratrulezzz May I ask what your goal is with all these changes and your fork?

Maybe an alternative for you would be to contribute to this original library instead of making a copy and putting your name on it?

**Comment by p1ratrulezzz** [comment]
Ah this was very specific case, I needed to run some commands before previous commands. I'm not sure if I can provide a good solution for now because still investigating into the code. If I come up with idea I'll send a correct pull request of course

**Comment by noplanman** [comment]
Feel free to open an issue with your specific use-case :+1: 

If it's a general problem, it would be best to have a proper solution in case other users are experiencing the same thing.

**Pull request closed without merging**
