### PR TITLE
Move to PHP 7.2+, fix up all strict variable and parameter types

### PR DESCRIPTION
**Pull request by noplanman**
| ?            |  !
|---           | ---
| Type         | improvement
| BC Break     | yes
| Fixed issues | n/a

#### Summary

This PR sets the minimum requirement to PHP 7.2.
Introduce strictly typed parameters and return types.

### CODE REVIEW

**Comment by noplanman** [comment]
@KristobalJunta I'd highly appreciate it if you could test this pretty big PR, to see if you run into any problems that could help put together a migration guide.

So if you have some time and a test environment for your bot, that would be awesome, thanks 😊

**Comment by KristobalJunta** [comment]
@noplanman sure!

**Comment by noplanman** [comment]
@jacklul Would appreciate your feedback too, as time permits :pray:

**Comment by jacklul** [comment]
> @jacklul Would appreciate your feedback too, as time permits 🙏

I don't really have time to closely look into it other than to say that this is a good change and direction

**Comment by noplanman** [comment]
@KristobalJunta Had a chance to try this yet? Any feedback?

**Comment by akalongman** [comment]
@noplanman do we plan to release a major version?

**Comment by noplanman** [comment]
@akalongman 1 step closer 😇

**Comment by akalongman** [comment]
@noplanman I just took a quick view. Will test when I have free time. I think its important PR. 

Whaqt do you think about PSR-12 coding standard?

**Comment by noplanman** [comment]
Cool, thanks! Would be great to get this merged, as it's a big step forward.

I'm happy with PSR-12, but PSR-2 is great too. As long as everybody sticks to the same thing it works for me 😅
Wha do you ask?

**Comment by akalongman** [comment]
@noplanman I want to send a PR with the reformatting of the codebase according to PSR-12. But first, let's make this PR merged. I'll review it in this week

**Comment by noplanman** [comment]
@akalongman I thought it is already PSR-12 compliant 🤔 

Anyways, I'll merge your latest PRs into this one, then you can take a look and do some testing.

**Pull request merged**
