### PR TITLE
Helper for sending `InputMedia` objects

### PR DESCRIPTION
**Pull request by noplanman**
Neat little internal helper to simplify the passing of files to media related methods.

Basically, it automatically generated multipart fields with the attached files and links them automagically.

~~*todo*: Same procedure for `thumb` fields.~~

```php
Request::sendMediaGroup([
    'chat_id'  => $chat_id,
    'media'    => [
        new InputMediaPhoto(['media' => '/path/to/some/photo.png']), // direct path as string is now possible too!
        new InputMediaVideo(['media' => Request::encodeFile('/path/to/my/video.mp4'))]),
        new InputMediaPhoto(['media' => Request::encodeFile('/path/to/another/photo.png']),
    ],
]);
```
instead of
```php
Request::sendMediaGroup([
    'chat_id'  => $chat_id,
    'photo_1'  => Request::encodeFile('/path/to/some/photo.png'),
    'photo_2'  => Request::encodeFile('/path/to/another/photo.png'),
    'my_video' => Request::encodeFile('/path/to/my/video.mp4'),
    'media'    => [
        new InputMediaPhoto(['media' => 'attach://photo_1']),
        new InputMediaVideo(['media' => 'attach://my_video']),
        new InputMediaPhoto(['media' => 'attach://photo_2']),
    ],
]);
```

and

```php
Request::editMessageMedia([
    'chat_id'    => $chat_id,
    'message_id' => $message_id,
    'media'      => new InputMediaPhoto([
        'caption' => 'New Caption!',
        'media'   => '/path/to/some/photo.png',
    ]),
]);
```
instead of
```php
Request::editMessageMedia([
    'chat_id'    => $chat_id,
    'message_id' => $message_id,
    'photo_1'    => Request::encodeFile('/path/to/some/photo.png'),
    'media'      => new InputMediaPhoto([
        'caption' => 'New Caption!',
        'media'   => 'attach://photo_1',
    ]),
]);
```

### CODE REVIEW

**Comment by noplanman** [comment]
@jacklul Absolutely agreed, as stated in the API too. Will do the same for any other methods that return an array of objects :+1:

**Comment by noplanman** [comment]
@jacklul Please take a look now. Have also made the whole return object process more bulletproof by remembering the current action, instead of trying to guess it by object fields.

**Comment by noplanman** [comment]
@jacklul What do you think of extending this even further and making it only necessary to pass the local file path, instead of `Request::encodeFile(...)`? Or rather, support both, and if a string is sent, then check if a local file exists or if it's a URL.

**Comment by jacklul** [comment]
@noplanman That sounds good

**Comment by noplanman** [comment]
@jacklul Check out the latest commit, basically allows absolute paths to be passed as strings for all available `InputFile` fields :tada: 

```php
Request::sendPhoto([
   ...
   'photo' => '/path/to/photo.jpg',
   ...
]);
```

**Comment by aaamina** [comment]
Fatal error: Class Longman\TelegramBot\Entities\InputMedia\InputMediaPhoto contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Longman\TelegramBot\Entities\InputMedia\InputMedia::getType, Longman\TelegramBot\Entities\InputMedia\InputMedia::getMedia, Longman\TelegramBot\Entities\InputMedia\InputMedia::setMedia) in G:\project\divar_bot\vendor\longman\telegram-bot\src\Entities\InputMedia\InputMediaPhoto.php on line 37


after new changes, I keep getting this error

**Comment by noplanman** [comment]
@aaamina Thanks for reporting this! I'm working on a fix right now :+1: 

(Next time, please open a new issue, makes it easier to find in the future, thanks :smiley:)

**Pull request merged**
