### PR TITLE
Speed up clean query

### PR DESCRIPTION
**Pull request by dva-re**
| ?            |  !
|---           | ---
| Type         |  improvement
| BC Break     |  no
| Fixed issues | #1138

#### Summary

Wrapped the query a bit for optimization

### CODE REVIEW

**Comment by noplanman** [comment]
Hi @dva-re thanks for the PR!

Can you provide some stats that show the improvements?

(Unfortunately I don't have any bot databases that are big enough to notice a significant difference)

**Comment by dva-re** [comment]
Hi @noplanman 

I have already done the cleaning, but before that I had not started it for half a year, and therefore the bot started to work very slowly.

The standard cleanup had to be canceled by hand about an hour after launch, since it was still executing the first request in a 10 thousand cycle.

After the request was rewritten, the cleanup took about a minute.

**Comment by noplanman** [comment]
@dva-re Please add an entry to the CHANGELOG in the `Changed` section, then I'll merge here, thanks!

**Comment by dva-re** [comment]
> @dva-re Please add an entry to the CHANGELOG in the `Changed` section, then I'll merge here, thanks!

done

**Comment by noplanman** [comment]
Thanks so much @dva-re 🙏

**Pull request merged**
