### PR TITLE
Allow to store in notes unicode, like cyrillic

### PR DESCRIPTION
**Pull request by volandku**
bug / improvement

### CODE REVIEW

**Comment by noplanman** [comment]
@volandku Thanks for your PR!

Does the string not get escaped correctly / what output do you get?
What version of PHP are you using?

`json_decode` *should* restore any saved string correctly.

**Comment by noplanman** [comment]
@volandku Just pinging again here to ask what exactly isn't working.

If something is off, would be great to have this fixed in the next release :muscle:

**Comment by volandku** [comment]
Well, I dont remenber for now ))
Seems that result in cyrillic didn`t store at all or stored in wrong format in DB

**Comment by noplanman** [comment]
@volandku Ok, thanks for getting back to me.

I'll close this off for now, as I can't reproduce this, but please do open it again with some example code if it happens again to you! :smiley:

**Comment by VSMent** [comment]
This is really useful. 
Debug, manual db edit or faster manual search are much better now.

**Comment by noplanman** [comment]
@VSMent Would you mind elaborating?
I assume you're talking about the change in this PR?

**Comment by VSMent** [comment]
@noplanman Well, actually even after development. 
I do not know what are cons of storing data with unescaped unicode. For me understandable cyrillic characters is huge pro.

P.S. What is PR?

**Comment by noplanman** [comment]
PR is short for Pull Request.

@VSMent What I meant to ask is, do you also require the change proposed here to be able to store cyrillic characters to the database? If so, could you provide me with a code example that fails so that I can test this and fix it please?

**Comment by VSMent** [comment]
@noplanman Everything works good. But when using PhpStorm or phpMyAdmin to view database tables I do not understand what is written in those cells.
I get "\u0422\u0430\u043A" instead of "Так" → "Yes" in Ukrainian.
It will be preferable for me (and hope for other Cyrillic language developers) to store unicode unescaped.

**Comment by noplanman** [comment]
Aaah, I see now, thanks for the explanation :+1:

I guess then the only "problem" would be interfaces (for viewing the DB fields) that don't support certain encodings. Not sure if that would actually matter though, as the same would apply in other DB fields like messages or user details with special characters.

@volandku Could you add an entry to the CHANGELOG.md in the "Unreleased" section please?

**Pull request merged**
